title: Cristiano Cunha personal blog on automation and testing.
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on automation and testing.
permalink: ':title/'
baseurl: #"/blog" #"/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "http://cristianomcunha.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Cristiano Cunha 
author-img: cristiano-cunha.jpg 
about-author: I am a tester that loves automation. Always hungry to keep learning. 
social-twitter: melioth 
social-facebook: cristiano.morais.cunha 
social-github: cmcunha
social-linkedin: cristianomcunha
social-email: cristianocunhablog@gmail.com

# Disqus
discus-identifier: cristianomcunha-com # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
remote_theme: artemsheludko/flexible-jekyll
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
